account/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [ 
    path('signup/', SignUpView.as_view(), name='signup'),
]

blogs/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic import TemplateView   

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

account/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Publication(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

account/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.

class SignUpView(CreateView):

    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

blogs/views.py
from django.shortcuts import render
from .models import Publication
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# Create your views here.

class BlogListView(ListView):
    model = Publication
    template_name = 'home.html'

class BlogCreateView(CreateView):
    model = Publication
    template_name = 'post_new.html'
    fields = ['title', 'body', 'author']

class BlogDetailView(DetailView):
    model = Publication
    template_name = 'post_detail.html'

class BlogUpdateView(UpdateView):
    model = Publication
    template_name = 'post_edit.html'
    fields = ['title', 'body']

class BlogDeleteView(DeleteView):
    model = Publication
    template_name = 'post_delete.html'
    fields = ['title', 'body']
    success_url = reverse_lazy('home')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Rum Online</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
        <header>
            <h1><a href="{% url 'home' %}">Rum Blog</a></h1>
        </header>
        <h2><a href="{% url 'post_new' %}">Post New</a></h2>
        <section>
            {% block content %}
            {% endblock content %}
        </section>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated%}
        HOLA {{ user.name }} :)
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Log Out</button>
        </form>
    {% else %}
        <p>NO ESTAS REGISTRADO</p>
        <a href="{% url 'login' %}">Log in</a>
        <a href="{% url 'signup' %}">Sign up</a>
    {% endif %}

    {% for publication in publication_list %}
        <h2><a href="{% url 'post_detail' publication.pk %}">{{ publication.title }}</a></h2>
        <p>{{ publication.author }}</p>
    {% endfor %}
{% endblock content %}

templates/post_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete post</h1>
    <form method="post">{% csrf_token %}
        <p>¿Esta seguro de borrar {{ publication.title }}?</p>
       <button type="submit" >Delete</button>
    </form>
{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>{{ publication.title }}
    <p>{{ publication.body }}</p>
    <a href="{% url 'post_edit' publication.pk %}">Edit</a>
    <a href="{% url 'post_delete' publication.pk %}">Delete</a> 
{% endblock content %}

templates/post_edit.html
{% extends "base.html" %}

{% block content %}
    <h1>Edit post</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p}}
        <button type="submit" >Update</button>
    </form>
{% endblock content %}

templates/post_new.html
{% extends "base.html" %}

{% block content %}
    <h1>New Post</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
        </form>
{% endblock content %}